<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[After navigate back URL https://www.saucedemo.com/inventory.html]]>
    </line>
  </reporter-output>
  <suite started-at="2023-12-18T20:39:11 IST" name="Suite" finished-at="2023-12-18T20:39:47 IST" duration-ms="36042">
    <groups>
    </groups>
    <test started-at="2023-12-18T20:39:11 IST" name="Test" finished-at="2023-12-18T20:39:47 IST" duration-ms="36042">
      <class name="testClasses.LogIn">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testClasses.LogIn@65e61854]" started-at="2023-12-18T20:39:11 IST" name="setUp" finished-at="2023-12-18T20:39:11 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:testClasses.LogIn@65e61854]" started-at="2023-12-18T20:39:11 IST" name="launchBrowser" finished-at="2023-12-18T20:39:14 IST" duration-ms="3355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="verifyLoginPage()[pri:1, instance:testClasses.LogIn@65e61854]" started-at="2023-12-18T20:39:14 IST" name="verifyLoginPage" finished-at="2023-12-18T20:39:24 IST" duration-ms="9452" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPage -->
        <test-method signature="verifyCurrentUrl()[pri:0, instance:testClasses.LogIn@65e61854]" started-at="2023-12-18T20:39:24 IST" name="verifyCurrentUrl" finished-at="2023-12-18T20:39:37 IST" depends-on-methods="testClasses.LogIn.verifyLoginPage" duration-ms="12709" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCurrentUrl -->
        <test-method signature="verifyProductsPage()[pri:0, instance:testClasses.LogIn@65e61854]" started-at="2023-12-18T20:39:37 IST" name="verifyProductsPage" finished-at="2023-12-18T20:39:41 IST" depends-on-methods="testClasses.LogIn.verifyCurrentUrl" duration-ms="4148" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[After navigate back URL https://www.saucedemo.com/inventory.html]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyProductsPage -->
        <test-method signature="verifyPriceDynamically()[pri:0, instance:testClasses.LogIn@65e61854]" started-at="2023-12-18T20:39:41 IST" name="verifyPriceDynamically" finished-at="2023-12-18T20:39:46 IST" depends-on-methods="testClasses.LogIn.verifyProductsPage" duration-ms="5403" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[I am in Your Cart Page expected [Your Cart12333] but found [Your Cart]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: I am in Your Cart Page expected [Your Cart12333] but found [Your Cart]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at testClasses.LogIn.verifyPriceDynamically(LogIn.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPriceDynamically -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:testClasses.LogIn@65e61854]" started-at="2023-12-18T20:39:47 IST" name="closeBrowser" finished-at="2023-12-18T20:39:47 IST" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testClasses.LogIn -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
